# H2内存数据库配置（用于快速测试）
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:competition_db;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;IGNORE_UNKNOWN_SETTINGS=TRUE;CHARSET=UTF-8
    username: sa
    password: 
  
  h2:
    console:
      enabled: true
      path: /h2-console
  
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    root: INFO
    com.nanhai: DEBUG

